name: Deployment
on:
  workflow_dispatch:

env:
  IMAGE_NAME: springboot-app

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version_step.outputs.NEW_VERSION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # IMPORTANT for tags

      - name: Generate Version
        id: version_step
        run: |
          chmod +x scripts/version.sh
          ./scripts/version.sh

  deploy:
    needs: version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: |
          echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

      - name: Run Deployment Script
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh ${{ needs.version.outputs.new_version }}
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          APP_NAME: YOUR_APP_NAME
          RESOURCE_GROUP: YOUR_RESOURCE_GROUP